"use client";

import { useState } from "react";
import { X, Sparkles, Copy, Check, Download, Loader2, FileText, Target, CheckCircle, Lightbulb } from "lucide-react";
import { apiRequest } from "@/lib/api";

interface MeetingSummaryModalProps {
    isOpen: boolean;
    onClose: () => void;
    transcript: string;
    duration: string;
    participantCount: number;
}

interface SummaryData {
    summary: string;
    keyPoints: string[];
    actionItems: string[];
    decisions: string[];
}

export function MeetingSummaryModal({ isOpen, onClose, transcript, duration, participantCount }: MeetingSummaryModalProps) {
    const [loading, setLoading] = useState(false);
    const [summaryData, setSummaryData] = useState<SummaryData | null>(null);
    const [copied, setCopied] = useState(false);

    if (!isOpen) return null;

    const generateSummary = async () => {
        setLoading(true);
        try {
            const data = await apiRequest("/ai/summary", {
                transcript,
                duration,
                participantCount,
            }, "POST");
            setSummaryData(data);
        } catch (err) {
            setSummaryData({
                summary: "Failed to generate summary. Please check your API key.",
                keyPoints: [],
                actionItems: [],
                decisions: [],
            });
        }
        setLoading(false);
    };

    const getMarkdown = () => {
        if (!summaryData) return "";
        let md = `# Meeting Summary\n\n`;
        md += `**Duration:** ${duration} | **Participants:** ${participantCount}\n\n`;
        md += `## Overview\n${summaryData.summary}\n\n`;
        if (summaryData.keyPoints.length > 0) {
            md += `## Key Points\n${summaryData.keyPoints.map(p => `- ${p}`).join("\n")}\n\n`;
        }
        if (summaryData.actionItems.length > 0) {
            md += `## Action Items\n${summaryData.actionItems.map(a => `- [ ] ${a}`).join("\n")}\n\n`;
        }
        if (summaryData.decisions.length > 0) {
            md += `## Decisions\n${summaryData.decisions.map(d => `- ${d}`).join("\n")}\n\n`;
        }
        md += `---\n*Generated by OneStudios AI*`;
        return md;
    };

    const handleCopy = async () => {
        await navigator.clipboard.writeText(getMarkdown());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const blob = new Blob([getMarkdown()], { type: "text/markdown" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `meeting-summary-${Date.now()}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-background border border-border rounded-2xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden animate-in zoom-in-95 duration-300 max-h-[85vh] flex flex-col">
                {/* Header */}
                <div className="flex items-center justify-between p-5 border-b border-border shrink-0">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500/20 to-purple-500/20 flex items-center justify-center border border-violet-500/30">
                            <Sparkles className="text-violet-500" size={20} />
                        </div>
                        <div>
                            <h2 className="font-bold text-lg text-foreground">AI Meeting Summary</h2>
                            <p className="text-xs text-muted-foreground">{duration} · {participantCount} participants</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-2 rounded-xl hover:bg-muted transition-colors">
                        <X size={20} />
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-5">
                    {!summaryData && !loading && (
                        <div className="flex flex-col items-center justify-center py-12 gap-4">
                            <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-violet-500/20 to-purple-500/20 flex items-center justify-center">
                                <Sparkles size={32} className="text-violet-500" />
                            </div>
                            <p className="text-sm text-muted-foreground text-center max-w-xs">
                                AI will analyze your meeting transcript and generate a structured summary with key points and action items.
                            </p>
                            <button
                                onClick={generateSummary}
                                disabled={!transcript}
                                className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-xl font-semibold hover:opacity-90 transition-all disabled:opacity-30 shadow-lg"
                            >
                                <Sparkles size={18} />
                                Generate Summary
                            </button>
                            {!transcript && (
                                <p className="text-xs text-amber-500">No transcript available. Speak during the call to build a transcript.</p>
                            )}
                        </div>
                    )}

                    {loading && (
                        <div className="flex flex-col items-center justify-center py-16 gap-3">
                            <div className="relative">
                                <Loader2 size={40} className="text-violet-500 animate-spin" />
                                <Sparkles size={16} className="text-purple-400 absolute -top-1 -right-1 animate-pulse" />
                            </div>
                            <p className="text-sm font-medium text-foreground">Analyzing your meeting...</p>
                            <p className="text-xs text-muted-foreground">This takes a few seconds</p>
                        </div>
                    )}

                    {summaryData && !loading && (
                        <div className="space-y-5">
                            {/* Summary */}
                            <div className="space-y-2">
                                <div className="flex items-center gap-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                                    <FileText size={14} /> Overview
                                </div>
                                <p className="text-sm text-foreground leading-relaxed bg-muted/30 p-4 rounded-xl border border-border">
                                    {summaryData.summary}
                                </p>
                            </div>

                            {/* Key Points */}
                            {summaryData.keyPoints.length > 0 && (
                                <div className="space-y-2">
                                    <div className="flex items-center gap-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                                        <Target size={14} /> Key Points
                                    </div>
                                    <ul className="space-y-1.5">
                                        {summaryData.keyPoints.map((point, i) => (
                                            <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                                                <span className="w-5 h-5 rounded-full bg-primary/15 text-primary flex items-center justify-center shrink-0 mt-0.5 text-[10px] font-bold">{i + 1}</span>
                                                {point}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            )}

                            {/* Action Items */}
                            {summaryData.actionItems.length > 0 && (
                                <div className="space-y-2">
                                    <div className="flex items-center gap-2 text-xs font-semibold text-amber-500 uppercase tracking-wider">
                                        <CheckCircle size={14} /> Action Items
                                    </div>
                                    <ul className="space-y-1.5">
                                        {summaryData.actionItems.map((item, i) => (
                                            <li key={i} className="flex items-start gap-2 text-sm text-foreground bg-amber-500/5 px-3 py-2 rounded-lg border border-amber-500/10">
                                                <span className="text-amber-500 mt-0.5">☐</span>
                                                {item}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            )}

                            {/* Decisions */}
                            {summaryData.decisions.length > 0 && (
                                <div className="space-y-2">
                                    <div className="flex items-center gap-2 text-xs font-semibold text-green-500 uppercase tracking-wider">
                                        <Lightbulb size={14} /> Decisions Made
                                    </div>
                                    <ul className="space-y-1.5">
                                        {summaryData.decisions.map((dec, i) => (
                                            <li key={i} className="flex items-start gap-2 text-sm text-foreground bg-green-500/5 px-3 py-2 rounded-lg border border-green-500/10">
                                                <span className="text-green-500 mt-0.5">✓</span>
                                                {dec}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            )}
                        </div>
                    )}
                </div>

                {/* Footer */}
                {summaryData && (
                    <div className="p-4 border-t border-border flex items-center justify-between shrink-0">
                        <p className="text-[10px] text-muted-foreground">Powered by Gemini AI</p>
                        <div className="flex items-center gap-2">
                            <button
                                onClick={handleCopy}
                                className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-medium transition-all ${copied ? "bg-green-500/15 text-green-600" : "bg-muted hover:bg-muted/80 text-foreground"}`}
                            >
                                {copied ? <Check size={14} /> : <Copy size={14} />}
                                {copied ? "Copied!" : "Copy"}
                            </button>
                            <button
                                onClick={handleDownload}
                                className="flex items-center gap-1.5 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-xs font-medium hover:opacity-90 transition-all"
                            >
                                <Download size={14} /> Download
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
