"use client";

import { useState } from "react";
import { X, Sparkles, Copy, Check, Download, Loader2, FileText, Target, CheckCircle, Lightbulb } from "lucide-react";
import { apiRequest } from "@/lib/api";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { TranscriptRenderer } from "@/components/TranscriptRenderer";
import type { ClientActionItem } from "@/components/ActionItemsTab";

interface MeetingSummaryModalProps {
    isOpen: boolean;
    onClose: () => void;
    transcript: string;
    duration: string;
    participantCount: number;
    actionItems?: ClientActionItem[];
}

interface SummaryData {
    summary: string;
    keyPoints: string[];
    actionItems: string[];
    decisions: string[];
}

export function MeetingSummaryModal({ isOpen, onClose, transcript, duration, participantCount, actionItems = [] }: MeetingSummaryModalProps) {
    const [loading, setLoading] = useState(false);
    const [summaryData, setSummaryData] = useState<SummaryData | null>(null);
    const [copied, setCopied] = useState(false);

    if (!isOpen) return null;

    const generateSummary = async () => {
        setLoading(true);
        try {
            const data = await apiRequest("/ai/summary", {
                transcript,
                duration,
                participantCount,
            }, "POST");
            setSummaryData(data);
        } catch {
            setSummaryData({
                summary: "Failed to generate summary. Please check your API key.",
                keyPoints: [],
                actionItems: [],
                decisions: [],
            });
        }
        setLoading(false);
    };

    const getMarkdown = () => {
        if (!summaryData) return "";
        let md = `# Meeting Summary\n\n`;
        md += `**Duration:** ${duration} | **Participants:** ${participantCount}\n\n`;
        md += `## Overview\n${summaryData.summary}\n\n`;
        if (summaryData.keyPoints.length > 0) {
            md += `## Key Points\n${summaryData.keyPoints.map(p => `- ${p}`).join("\n")}\n\n`;
        }
        if (summaryData.actionItems.length > 0 || actionItems.length > 0) {
            md += `## Action Items\n${formatMarkdownActionItems(actionItems, summaryData.actionItems)}\n\n`;
        }
        if (summaryData.decisions.length > 0) {
            md += `## Decisions\n${summaryData.decisions.map(d => `- ${d}`).join("\n")}\n\n`;
        }
        md += `---\n*Generated by SyncHub AI*`;
        return md;
    };

    const handleCopy = async () => {
        await navigator.clipboard.writeText(getMarkdown());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const blob = new Blob([getMarkdown()], { type: "text/markdown" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `meeting-summary-${Date.now()}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="fixed inset-0 z-[200] flex items-center justify-center bg-[rgb(6_6_8/0.7)] backdrop-blur-[40px]">
            <div className="mx-4 flex max-h-[85vh] w-full max-w-[560px] flex-col overflow-hidden rounded-xl border border-[rgb(255_255_255/0.08)] bg-[#111115] shadow-2xl">
                {/* Header */}
                <div className="flex items-center justify-between p-5 border-b border-[rgb(255_255_255/0.06)] shrink-0">
                    <div className="flex items-center gap-3">
                        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[rgb(167_139_250/0.14)]">
                            <Sparkles className="text-[#a78bfa]" size={18} />
                        </div>
                        <div>
                            <h2 className="font-medium text-base text-[#f1f1f3]" style={{ fontFamily: "var(--font-geist), var(--font-body), ui-sans-serif, system-ui, sans-serif" }}>
                                AI Meeting Summary
                            </h2>
                            <p className="text-[11px] text-[#8b8b9a]" style={{ fontFamily: "var(--font-geist-mono), ui-monospace, monospace" }}>
                                {duration} · {participantCount} participants
                            </p>
                        </div>
                    </div>
                    <button
                        onClick={onClose}
                        className="rounded-lg p-2 text-[#8b8b9a] transition-colors hover:bg-[rgb(255_255_255/0.06)] hover:text-[#f1f1f3]"
                        aria-label="Close summary"
                    >
                        <X size={18} />
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-5">
                    <Tabs defaultValue="summary" className="space-y-4">
                        <TabsList className="grid w-full grid-cols-3 bg-[rgb(255_255_255/0.04)] rounded-lg p-0.5">
                            <TabsTrigger value="summary" className="rounded-md text-xs data-[state=active]:bg-[rgb(167_139_250/0.14)] data-[state=active]:text-[#a78bfa] data-[state=active]:shadow-none">Summary</TabsTrigger>
                            <TabsTrigger value="actions" className="rounded-md text-xs data-[state=active]:bg-[rgb(167_139_250/0.14)] data-[state=active]:text-[#a78bfa] data-[state=active]:shadow-none">Action Items</TabsTrigger>
                            <TabsTrigger value="transcript" className="rounded-md text-xs data-[state=active]:bg-[rgb(167_139_250/0.14)] data-[state=active]:text-[#a78bfa] data-[state=active]:shadow-none">Transcript</TabsTrigger>
                        </TabsList>

                        <TabsContent value="summary" className="mt-0">
                            {!summaryData && !loading && (
                                <div className="flex flex-col items-center justify-center py-12 gap-4">
                                    <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-[rgb(167_139_250/0.14)]">
                                        <Sparkles size={28} className="text-[#a78bfa]" />
                                    </div>
                                    <p className="text-sm text-[#8b8b9a] text-center max-w-xs" style={{ fontFamily: "var(--font-geist), var(--font-body), ui-sans-serif, system-ui, sans-serif" }}>
                                        AI will analyze your meeting transcript and generate a structured summary with key points and action items.
                                    </p>
                                    <button
                                        onClick={generateSummary}
                                        disabled={!transcript}
                                        className="flex items-center gap-2 rounded-lg bg-[#a78bfa] px-5 py-2.5 text-sm font-medium text-[#060608] transition-all hover:opacity-90 disabled:opacity-30"
                                    >
                                        <Sparkles size={16} />
                                        Generate Summary
                                    </button>
                                    {!transcript && (
                                        <p className="text-xs text-[#facc15]">No transcript available. Speak during the call to build a transcript.</p>
                                    )}
                                </div>
                            )}

                            {loading && (
                                <div className="flex flex-col items-center justify-center py-16 gap-3">
                                    <div className="relative">
                                        <Loader2 size={36} className="text-[#a78bfa] animate-spin" />
                                        <Sparkles size={14} className="absolute -right-1 -top-1 text-[#a78bfa] animate-pulse" />
                                    </div>
                                    <p className="text-sm text-[#8b8b9a]" style={{ fontFamily: "var(--font-geist), var(--font-body), ui-sans-serif, system-ui, sans-serif" }}>
                                        Analyzing your meeting...
                                    </p>
                                    <p className="text-xs text-[#8b8b9a]/60">This takes a few seconds</p>
                                </div>
                            )}

                            {summaryData && !loading && (
                                <SummaryTabContent summaryData={summaryData} />
                            )}
                        </TabsContent>

                        <TabsContent value="actions" className="mt-0">
                            <StructuredActionItems actionItems={actionItems} fallbackItems={summaryData?.actionItems ?? []} />
                        </TabsContent>

                        <TabsContent value="transcript" className="mt-0">
                            <TranscriptRenderer transcript={transcript} />
                        </TabsContent>
                    </Tabs>
                </div>

                {/* Footer */}
                {summaryData && (
                    <div className="p-4 border-t border-[rgb(255_255_255/0.06)] flex items-center justify-between shrink-0">
                        <p className="text-[10px] text-[#8b8b9a]" style={{ fontFamily: "var(--font-geist-mono), ui-monospace, monospace" }}>Powered by Gemini AI</p>
                        <div className="flex items-center gap-2">
                            <button
                                onClick={handleCopy}
                                className={`flex items-center gap-1.5 rounded-lg px-4 py-2 text-xs font-medium transition-all ${copied
                                    ? "bg-[rgb(88_214_141/0.14)] text-[#58d68d]"
                                    : "border border-[rgb(255_255_255/0.06)] bg-[rgb(255_255_255/0.03)] text-[#8b8b9a] hover:bg-[rgb(255_255_255/0.06)] hover:text-[#f1f1f3]"
                                    }`}
                            >
                                {copied ? <Check size={14} /> : <Copy size={14} />}
                                {copied ? "Copied!" : "Copy Markdown"}
                            </button>
                            <button
                                onClick={handleDownload}
                                className="flex items-center gap-1.5 px-4 py-2 bg-[#00d9f5] text-[#060608] rounded-lg text-xs font-medium hover:opacity-90 transition-all"
                            >
                                <Download size={14} /> Download .md
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}

function SummaryTabContent({ summaryData }: { summaryData: SummaryData }) {
    return (
        <div className="space-y-5">
            {/* Overview */}
            <div className="space-y-2">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase text-[#8b8b9a]">
                    <FileText size={14} /> Overview
                </div>
                <div className="border-b border-[rgb(255_255_255/0.06)]" />
                <p className="rounded-lg bg-[rgb(255_255_255/0.03)] border border-[rgb(255_255_255/0.06)] p-4 text-sm leading-relaxed text-[#f1f1f3]">
                    {summaryData.summary}
                </p>
            </div>

            {/* Key Points */}
            {summaryData.keyPoints.length > 0 && (
                <div className="space-y-2">
                    <div className="flex items-center gap-2 text-xs font-semibold uppercase text-[#8b8b9a]">
                        <Target size={14} /> Key Points
                    </div>
                    <div className="border-b border-[rgb(255_255_255/0.06)]" />
                    <ul className="space-y-1.5">
                        {summaryData.keyPoints.map((point, i) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-[#f1f1f3]">
                                <span className="w-5 h-5 rounded-full bg-[rgb(0_217_245/0.14)] text-[#00d9f5] flex items-center justify-center shrink-0 mt-0.5 text-[10px] font-bold">{i + 1}</span>
                                {point}
                            </li>
                        ))}
                    </ul>
                </div>
            )}

            {/* Decisions */}
            {summaryData.decisions.length > 0 && (
                <div className="space-y-2">
                    <div className="flex items-center gap-2 text-xs font-semibold uppercase text-[#58d68d]">
                        <Lightbulb size={14} /> Decisions Made
                    </div>
                    <div className="border-b border-[rgb(255_255_255/0.06)]" />
                    <ul className="space-y-1.5">
                        {summaryData.decisions.map((dec, i) => (
                            <li key={i} className="flex items-start gap-2 rounded-lg border border-[rgb(88_214_141/0.1)] bg-[rgb(88_214_141/0.05)] px-3 py-2 text-sm text-[#f1f1f3]">
                                <CheckCircle size={14} className="mt-0.5 shrink-0 text-[#58d68d]" />
                                {dec}
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
    );
}

function StructuredActionItems({ actionItems, fallbackItems }: { actionItems: ClientActionItem[]; fallbackItems: string[] }) {
    if (actionItems.length === 0 && fallbackItems.length === 0) {
        return (
            <div className="rounded-lg border border-[rgb(255_255_255/0.06)] bg-[rgb(255_255_255/0.03)] px-4 py-6 text-center text-sm text-[#8b8b9a]">
                No action items captured.
            </div>
        );
    }

    if (actionItems.length > 0) {
        return (
            <ul className="space-y-2">
                {actionItems.map((item) => (
                    <li key={item.id} className="flex items-start gap-2 rounded-lg border border-[rgb(250_204_21/0.1)] bg-[rgb(250_204_21/0.05)] px-3 py-2 text-sm text-[#f1f1f3]">
                        <CheckCircle size={14} className="mt-0.5 shrink-0 text-[#facc15]" />
                        <div>
                            <p>{item.text}</p>
                            {(item.owner || item.dueDate) && (
                                <p className="mt-1 text-[11px] text-[#8b8b9a]" style={{ fontFamily: "var(--font-geist-mono), ui-monospace, monospace" }}>
                                    {[item.owner ? `Owner: ${item.owner}` : null, item.dueDate ? `Due: ${formatDate(item.dueDate)}` : null].filter(Boolean).join(" · ")}
                                </p>
                            )}
                        </div>
                    </li>
                ))}
            </ul>
        );
    }

    return (
        <ul className="space-y-1.5">
            {fallbackItems.map((item, i) => (
                <li key={i} className="flex items-start gap-2 rounded-lg border border-[rgb(250_204_21/0.1)] bg-[rgb(250_204_21/0.05)] px-3 py-2 text-sm text-[#f1f1f3]">
                    <CheckCircle size={14} className="mt-0.5 shrink-0 text-[#facc15]" />
                    {item}
                </li>
            ))}
        </ul>
    );
}

function formatMarkdownActionItems(actionItems: ClientActionItem[], fallbackItems: string[]) {
    if (actionItems.length > 0) {
        return actionItems.map((item) => {
            const meta = [
                item.owner ? `Owner: ${item.owner}` : null,
                item.dueDate ? `Due: ${formatDate(item.dueDate)}` : null,
            ].filter(Boolean).join(" | ");
            return `- [ ] ${item.text}${meta ? ` (${meta})` : ""}`;
        }).join("\n");
    }

    return fallbackItems.map((item) => `- [ ] ${item}`).join("\n");
}

function formatDate(value: string) {
    const date = new Date(value);
    if (!Number.isFinite(date.getTime())) return value;
    return date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
}
